services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand:
      - apt-get update
      - apt-get install -y build-essential wget
      - wget http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz
      - tar -xvzf pa_stable_v190700_20210406.tgz
      - cd portaudio
      - ./configure && make
      - make install
    startCommand: gunicorn app:app