services:
  - type: web
    name: new_midi
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential wget portaudio19-dev libasound2-dev
    startCommand: gunicorn new_midi:new_midi